name: project-env

channels:
  - conda-forge

dependencies:
  - python=3.12
  - jupyter
  - jupytext
  - matplotlib
  - matplotlib-fontja
  - numpy
  - pandas
  - pytest

  # pip パッケージは uv 経由でインストールする（例: uv pip install -e ".[dev]"）
  - pip:
      - -e .[dev,test,optional]
