name: Create Release PR

on:
  push:
    branches:
      - 'dev'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create_release_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          git log --pretty=format:"%s" --grep="^feat:\|fix:\|docs:\|style:\|refactor:\|perf:\|test:\|chore:" > release-notes.md
          echo "::set-output name=notes::$(cat release-notes.md | awk '{printf "%s\\n", $0}')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: create release notes"
          branch: release-branch
          title: "Release PR"
          body: ${{ steps.generate_release_notes.outputs.notes }}
